### ISSUE TITLE
urgent11-detector failed to run

### ISSUE THREAD

**Issue by niknok236** [ArmisSecurity/urgent11-detector#1]
When testing, shows the following error: 
root@elkwsg910:~# urgent11-detector x.x.x.x 80
Traceback (most recent call last):
  File "/usr/local/bin/urgent11-detector", line 6, in <module>
    from urgent11_detector import main
  File "/usr/local/lib/python2.7/dist-packages/urgent11_detector.py", line 41, in <module>
    ICMP_TIMESTAMP_REQUEST_TRUNCATED = bytes.fromhex('0d00f2ff00000000')
AttributeError: type object 'str' has no attribute 'fromhex'

**Comment by kingoffoxes** [comment]
Also finding a similar issue:
user@PC:~$ urgent11-detector 192.168.1.1:80
Traceback (most recent call last):
  File "/home/user/.local/bin/urgent11-detector", line 7, in <module>
    from urgent11_detector import main
  File "/home/user/.local/lib/python2.7/site-packages/urgent11_detector.py", line 41, in <module>
    ICMP_TIMESTAMP_REQUEST_TRUNCATED = bytes.fromhex('0d00f2ff00000000')
AttributeError: type object 'str' has no attribute 'fromhex'

**Comment by DanBeard** [comment]
I had that issue in python2 but it worked in python3 for me (e.g.) :

pip3 install urgent11-detector
urgent11-detector 192.168.1.1 80

**Comment by dor-zusman** [comment]
Hey,
As @DanBeard helpfully mentioned, the detector indeed can run only under >= Python 3,
the documentation and the pypi package will be updated accordingly.

Thanks,
Dor
