### ISSUE TITLE
Fails to run under Python 3.7.4_1

### ISSUE THREAD

**Issue by Nuru** [ArmisSecurity/urgent11-detector#2]
I installed python3 via Homebrew on a Mac and tried several variations of ways to install urgent11-detector, but ultimately they all failed with the same stack trace:

```
$ urgent11-detector 
Traceback (most recent call last):
  File "/usr/local/bin/urgent11-detector", line 11, in <module>
    load_entry_point('urgent11-detector==0.1.1', 'console_scripts', 'urgent11-detector')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/urgent11_detector.py", line 25, in <module>
    import iptc
  File "/usr/local/lib/python3.7/site-packages/iptc/__init__.py", line 10, in <module>
    from iptc.ip4tc import (is_table_available, Table, Chain, Rule, Match, Target, Policy, IPTCError)
  File "/usr/local/lib/python3.7/site-packages/iptc/ip4tc.py", line 13, in <module>
    from .xtables import (XT_INV_PROTO, NFPROTO_IPV4, XTablesError, xtables,
  File "/usr/local/lib/python3.7/site-packages/iptc/xtables.py", line 812, in <module>
    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig': 'ldconfig'
```

I tried the simplest `pip install urgent11-detector` to the more complicated
```
pip install --force-reinstall --no-binary :all:  urgent11-detector
```

and they all had the same result.

My environment:
```
$ python --version
Python 3.7.4
$ pip list
Package           Version
----------------- -------
cairocffi         0.9.0  
CairoSVG          2.2.1  
cffi              1.11.5 
cssselect2        0.2.1  
defusedxml        0.5.0  
Pillow            5.3.0  
pip               19.1.1 
pycparser         2.19   
python-iptables   0.14.0 
scapy             2.4.3  
setuptools        41.4.0 
tinycss2          0.6.1  
urgent11-detector 0.1.1  
webencodings      0.5.1  
wheel             0.33.6 
```

**Comment by dor-zusman** [comment]
Hey Nuru,
You seem to have encountered a compatibility issue between the iptc python package your current machine setup and with good reason.
There is no netfilter (iptables) on macOS, so firewall rules cant be added the same way.
this will require some code to be changed in order to support macOS, which we may do in the future.
For the time being, please use a Linux machine to run the detector.

Thank you for bring this to our attention,
Dor
